config/routes.rb
Rails.application.routes.draw do
  resources :houses do
    collection do
      post 'search'
    end
  end
  resources :photos

 root 'houses#index'

end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos

  def self.search type, input, min = nil, max = nil
    if ["mls", "state", "zipcode"].include? type #exact match
      @houses = House.where("#{type} = ?", input)
    elsif type == "city" #partial match
      @houses = House.where("#{type} LIKE ?", '%'+input.to_s+'%')
    else ["bedrooms", "bathrooms", "square_feet"].include? type #range
      @houses = House.where("#{type} >= ? AND #{type} <= ?", min, max)
    end
    @houses
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :house

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
    5.times{ @house.photos.new }
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @houses = House.search(params[:type], params[:input], params[:min], params[:max])
    flash[:notice] =  "Search Results"
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:mls, :street_1, :street_2, :city, :state, :zipcode, :neighborhood, :sales_price, :date_listed, :bedrooms, :bathrooms, :garage_size, :square_feet, :lot_size, :description,
      :photos_attributes => [:title, :image])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <div class="form">
    <% if @house.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

        <ul>
        <% @house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :mls, "MLS #" %><br>
      <%= f.number_field :mls %>
    </div>
    <div class="field">
      <%= f.label :street_1, "Street Address" %><br>
      <%= f.text_field :street_1 %>
    </div>
    <div class="field">
      <%= f.label :street_2, "Address 2" %><br>
      <%= f.text_field :street_2 %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state %><br>
      <%= f.text_field :state %>
    </div>
    <div class="field">
      <%= f.label :zipcode %><br>
      <%= f.number_field :zipcode %>
    </div>
    <div class="field">
      <%= f.label :neighborhood %><br>
      <%= f.text_field :neighborhood %>
    </div>
    <div class="field">
      <%= f.label :sales_price %><br>
      <%= f.number_field :sales_price %>
    </div>
    <div class="field">
      <%= f.label :date_listed %><br>
      <%= f.date_select :date_listed %>
    </div>
    <div class="field">
      <%= f.label :bedrooms %><br>
      <%= f.number_field :bedrooms %>
    </div>
    <div class="field">
      <%= f.label :bathrooms %><br>
      <%= f.number_field :bathrooms %>
    </div>
    <div class="field">
      <%= f.label :garage_size %><br>
      <%= f.number_field :garage_size %>
    </div>
    <div class="field">
      <%= f.label :square_feet %><br>
      <%= f.number_field :square_feet %>
    </div>
    <div class="field">
      <%= f.label :lot_size %><br>
      <%= f.number_field :lot_size %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <%= f.fields_for :photos do |ff| %>
      <div>
        <%= ff.label :image, "Image #{ff.options[:child_index] + 1}" %>
        <%= ff.text_field :title %>
        <%= ff.file_field :image %>
      </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New House', new_house_path, class: "button" %>

<h1> House Results</h1>

<table>
  <thead>
    <tr>
      <th>MLS</th>
      <th>Street Addres</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Neighborhood</th>
      <th>Sales price</th>
      <th>Date listed</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Garage size</th>
      <th>Square feet</th>
      <th>Lot size</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.mls %></td>
        <td><%= house.street_1 %></td>
        <td><%= house.street_2 %></td>
        <td><%= house.city %></td>
        <td><%= house.state %></td>
        <td><%= house.zipcode %></td>
        <td><%= house.neighborhood %></td>
        <td><%= "$" + house.sales_price.to_s %></td>
        <td><%= house.date_listed.strftime("%m/%d/%Y")  %></td>
        <td><%= house.bedrooms %></td>
        <td><%= house.bathrooms %></td>
        <td><%= house.garage_size %></td>
        <td><%= house.square_feet %></td>
        <td><%= house.lot_size %></td>
        <td><%= house.description %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>MLS:</strong>
  <%= @house.mls %>
</p>

<p>
  <strong>Street Address:</strong>
  <%= @house.street_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @house.street_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @house.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @house.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @house.zipcode %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @house.neighborhood %>
</p>

<p>
  <strong>Sales price:</strong>
  <%= "$" + @house.sales_price.to_s %>
</p>

<p>
  <strong>Date listed:</strong>
  <%= @house.date_listed.strftime("%m/%d/%Y")  %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @house.bedrooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @house.bathrooms %>
</p>

<p>
  <strong>Garage size:</strong>
  <%= @house.garage_size %>
</p>

<p>
  <strong>Square feet:</strong>
  <%= @house.square_feet %>
</p>

<p>
  <strong>Lot size:</strong>
  <%= @house.lot_size %>
</p>

<p>
  <strong>Description:</strong>
  <%= @house.description %>
</p>

<p>
  <strong>Photos:</strong>
  <% @house.photos.each do |photo| %>
    <% if !photo.title.empty? %>
        <div>
          <%= photo.title %>
          <%= image_tag photo.image %>
        </div>
      <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fun Realtors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="search_form">
    <%= form_tag("/houses/search", method: "post") do %>
      <select id="search" name="type">
        <option value="mls">MLS#</<option>
        <option value="city">City</<option>
        <option value="state">State</<option>
        <option value="zipcode">Zipcode</<option>
        <option value="bedrooms"># Bedrooms</<option>
        <option value="bathrooms"># Bathrooms</<option>
        <option value="square_feet">Square Feet</<option>
      </select>
      <div id="search_name">
        <input type="text" name="input">
      </div>
      <div id="search_range" class="hidden">
        <input type="text" name="min" placeholder="min">
        <input type="text" name="max" placeholder="max"/>
      </div>
      <input type="submit" value="Search"/>
    <% end %>
  </div>
  <hr/>
  <%= yield %>
  <hr/>
  <div id="footer">
    &copy; 2018 Fun Realtors
  </div>
</body>
</html>